### PR TITLE
Added auth, profile page and Explore peers page functionalities

### PR DESCRIPTION
**Pull request by Devansu-Yadav**
This PR resolves issue #3 by making the following changes:

- Authentication with Firebase
- Create and Edit on the User profile page.
- User profile actions like Fetch profile details and Edit profile
- Signup, Login, and Logout functionality
- Follow and Unfollow other users.
- View other users profile page.
- Integrate User data like followers, following on Explore peers page.
- Fixed page reload bugs on all pages (due to state being lost).

Preview link for the changes: https://the-social-network-git-auth-devansu-yadav.vercel.app/

### CODE REVIEW

**Review by sri-rishi — CHANGES_REQUESTED** [review]
Going on other user profile it's show empty page 

image

**Review by sri-rishi — APPROVED** [review]
Code looks fine, couldn't find any major issue, reminder for removing `console.log` from code when done changing in app

**Review by samyakshah3008 — APPROVED** [review]
Clean code and UI 
Good use of semantic tags 
Good for approval

**Comment by Devansu-Yadav** [comment]
> Going on other user profile it's show empty page
> 
> image

Yupp, that's because the URL for visiting other users' page only supports `userId` and not `userName`. I'm looking to add that in future versions of the app.

**Comment by DivyanshSareen** [comment]
Everything looks great. Code is easy to read. Good to merge

**Pull request merged**
